import type { Metadata } from "next";
import localFont from "next/font/local";
import { Raleway } from "next/font/google";
import { Toaster } from "@wizloft/ui/components/sonner"

import "@wizloft/ui/globals.css";
import "./globals.css";

const raleway = Raleway({subsets:['latin'],variable:'--font-sans'});

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={raleway.variable}>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
				<Toaster
          richColors
          position="top-center"
          duration={3000}
        />
			</body>
		</html>
	);
}
